### PR TITLE
added source_mac, destination_mac, inner_vlan, and vlan to Logstash for Bro logs

### PR DESCRIPTION
**Pull request by ghost**
added source_mac, destination_mac, inner_vlan, and vlan to Logstash filters and Logstash field template should Bro enable vlan and mac address capturing

### CODE REVIEW

**Comment by ghost** [comment]
One comment: if the user doesn't have MAC and VLAN capturing enabled in Bro (see [the feature request](https://github.com/Security-Onion-Solutions/securityonion-bro-scripts/issues/2) I created), these changes to `1100_preprocess_bro_conn.conf` and `6000_bro.conf` shouldn't hurt anything, as those fields simply won't be present, **if** the user has JSON formatting of the logs enabled.

However, I suppose if they have CSV enabled instead, then the remaining fields at the end of the log (original country code, etc.) would get messed up?

**Comment by ghost** [comment]
Doing this also opens up future possibilities for using a MAC address OUI filter (like https://github.com/Vigilant-LLC/logstash-filter-ieee_oui, which I've used before) to create fields for network hardware vendors.

**Comment by mmguero** [comment]
```
@load policy/protocols/conn/vlan-logging
@load policy/protocols/conn/mac-logging
```

Is what I put in my `local.bro` file to enable these flags.

**Comment by ghost** [comment]
```
@load policy/protocols/conn/vlan-logging
@load policy/protocols/conn/mac-logging
```


Is what I put in my `local.bro` file to enable these fields.

**Comment by dougburks** [comment]
Hi @cement-berries ,

Thanks for creating the separate PRs!

I'm not totally opposed to this PR, but I would like to bring up a few points for discussion.

- I agree with your point above about CSV logging being problematic due to field ordering.
- When using AF_PACKET, VLAN tags aren't passed from the kernel to Bro.
- dhcp.log already has MAC addresses.
- Depending on network architecture and sensor placement, MAC addresses may not be all that helpful.
- Also need to consider impact to performance and/or storage requirements for additional logging.

Thoughts?

Thanks!

**Comment by ghost** [comment]
Those are all good points, some of which I had not considered.

My main use-case is actually post-processing PCAPs rather than live network capture, which I realize puts me in the vast minority of users I'm sure.

I'll leave it totally up to your discretion, of course. If you feel this isn't the best fit to get merged in, that's fine, it's easy enough to apply locally by hand when I need to.

EDIT: meant minority, not majority

**Comment by WSLUser** [comment]
>My main use-case is actually post-processing PCAPs rather than live network capture, which I realize puts me in the vast minority of users I'm sure.

You're not alone I assure you. There are many who do post-processing due to resource availability and not wanting to disrupt prod environments when capturing pcap data. I think this would be a great addition once tweaked to address dougburk's concerns (grab macs from dhcp.log, ensuring VLAN tags are passed to Bro, ensure csv logging isn't problematic, and finally documenting the updated compute and storage requirements and optimize as much as possible.

**Pull request closed without merging**
