### PR TITLE
A few improvements to securityonion-elastic: support MAC and VLAN from bro, minor fixes to so-import-pcap, and added a new so-elastic-document-stats script

### PR DESCRIPTION
**Pull request by ghost**
This merge request includes the following:

- A minor fix to the Logstash filter for Bro's files.log in the case of non-JSON formatted Bro logs (added missing extracted size columns to field list)
- Added source_mac, destination_mac, inner_vlan, and vlan to Logstash fields template and Logstash filter for Bro's conn.log should `policy/protocols/conn/vlan-logging` and `policy/protocols/conn/mac-logging` be loaded
- Handle PCAP filenames with spaces in them correctly in `so-import-pcap`
- Run bro from `so-import-pcap` with -C flag to handle PCAPs where checksumming may have been offloaded to the NIC in which case those packets may be dropped by Bro (assuming we want to see them, which I think we do)
- Added /usr/sbin/so-elastic-document-stats to show latest indexed document (optionally by event_type), logstash pipeline statistics, and elasticearch indices from command line

One thought: I'm not sure how to go about this, but I think in whatever default configuration SO ships the `local.bro` configuration as you should enable the following:

```
@load policy/protocols/conn/vlan-logging
@load policy/protocols/conn/mac-logging
```
In a network security environment, MAC addresses and VLANs are almost universally going to be a desirable piece of information to have. Maybe I will add a feature request? What repo is that in?

### CODE REVIEW

**Comment by ghost** [comment]
One other comment: even if the user doesn't have MAC and VLAN capturing enabled in Bro (see [the feature request](https://github.com/Security-Onion-Solutions/securityonion-bro-scripts/issues/2) I created), these changes to `1100_preprocess_bro_conn.conf` and `6000_bro.conf` shouldn't hurt anything, as those fields simply won't be present.

**Comment by dougburks** [comment]
Hi @cement-berries ,

Thanks for the PR!

Would it be possible for you to break this into separate PRs for each component?
- so-import-pcap
- so-elastic-document-stats
- mac/vlan changes (this may need further discussion)
- other logstash changes not related to mac/vlan changes

Thanks!

**Comment by mmguero** [comment]
Sure, I will do so.

**Comment by ghost** [comment]
I will do so

**Comment by ghost** [comment]
Closing pull request to split into multiple pull requests.

**Comment by ghost** [comment]
Done, split into https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/44, https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/45, https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/46, https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/47

**Pull request closed without merging**
